<?php
/**
 * Configuration
 * PHP version 7.2
 *
 * @category Class
 * @package  HelloUser\OpenAPI\V1\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * HelloUser
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HelloUser\OpenAPI\V1\Client;


use \OpenAPI\Client\Configuration\ConfigurationAbstract;

/**
 * Configuration Class Doc Comment
 * PHP version 7.2
 *
 * @category Class
 * @package  HelloUser\OpenAPI\V1\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Configuration extends ConfigurationAbstract
{
    /**
     * @var array
     */
    public static $additionalData = [
        
        'helloIdGet' => [
            'className' => 'HelloApi',
            'returnType' => '\HelloUser\OpenAPI\V1\Client\Model\HelloResult',
            'params' => [
                [
                    'paramName' => 'id',
                    'paramType' => 'string',
                    'required' => true,
                    'style' => 'simple',
                    'explode' => false
                ],
            ]
        ],
        'userIdGet' => [
            'className' => 'UserApi',
            'returnType' => '\HelloUser\OpenAPI\V1\Client\Model\UserResult',
            'params' => [
                [
                    'paramName' => 'id',
                    'paramType' => 'string',
                    'required' => true,
                    'style' => 'simple',
                    'explode' => false
                ],
            ]
        ],
        'userPost' => [
            'className' => 'UserApi',
            'returnType' => '\HelloUser\OpenAPI\V1\Client\Model\UserResult',
            'params' => [
                [
                    'paramName' => 'user',
                    'paramType' => '\HelloUser\OpenAPI\V1\Client\Model\User',
                    'required' => true,
                    'style' => '',
                    'explode' => false
                ],
            ]
        ],
    ];

    /**
     * The host
     *
     * @var string
     */
    protected $host = 'http://rollun-openapi/openapi/HelloUser/v1';

    /**
     * User agent of the HTTP request, set to "OpenAPI-Generator/{version}/PHP" by default
     *
     * @var string
     */
    protected $userAgent = 'OpenAPI-Generator/1.0.0/PHP';

    /**
     * Gets the essential information for debugging
     *
     * @return string The report for debugging
     */
    public static function toDebugReport()
    {
        $report  = 'PHP SDK (HelloUser\OpenAPI\V1\Client) Debug Report:' . PHP_EOL;
        $report .= '    OS: ' . php_uname() . PHP_EOL;
        $report .= '    PHP Version: ' . PHP_VERSION . PHP_EOL;
        $report .= '    The version of the OpenAPI document: 1' . PHP_EOL;
        $report .= '    Temp Folder Path: ' . self::getDefaultConfiguration()->getTempFolderPath() . PHP_EOL;

        return $report;
    }

    /**
     * Returns an array of host settings
     *
     * @return array an array of host settings
     */
    public function getHostSettings(): array
    {
        return [
            [
                "url" => "http://rollun-openapi/openapi/HelloUser/v1",
                "description" => "No description provided",
            ],
            [
                "url" => "http://localhost:8080/openapi/HelloUser/v1",
                "description" => "No description provided",
            ]
        ];
    }
}
