services:
  rollun-openapi:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm/8.1
      dockerfile: Dockerfile
      args:
        WWW_DATA_UID: ${DOCKER_USER_UID}
        WWW_DATA_GID: ${DOCKER_USER_GID}
    volumes:
      - ./:/var/www/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IS_DOCKER: 1
      PHP_IDE_CONFIG: serverName=rollun-openapi
      TEST_MANIFEST_HOST_INDEX: 2

  rollun-openapi-logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    volumes:
      - ./docker/logstash/config/:/usr/share/logstash/config/
