name: Test PHP 8.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # https://github.com/docker/compose/issues/7306
      COMPOSE_INTERACTIVE_NO_CLI: 1
    steps:
      - uses: actions/checkout@v2

      - name: Init project
        run: make init-8.0 test-8.0